# Generated by Django 3.2.18 on 2023-09-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
